server:
  port: 8087
fts:
  db:
    database: fts-recommendation
    host: 172.25.197.196
    pw: SQLPASSWORD
  swagger:
    title: WiseInvest推荐服务接口文档
    description: WiseInvest推荐服务接口文档
    package: com.seme.wiseinvest.controller