"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var vue_1 = require("vue");
var element_plus_1 = require("element-plus");
require("element-plus/dist/index.css");
var zh_cn_1 = require("element-plus/es/locale/lang/zh-cn");
require("./assets/main.css");
var router_1 = require("@/router");
var pinia_1 = require("pinia");
var pinia_plugin_persistedstate_1 = require("pinia-plugin-persistedstate");
var App_vue_1 = require("./App.vue");
var app = (0, vue_1.createApp)(App_vue_1.default);
var pinia = (0, pinia_1.createPinia)();
var persist = (0, pinia_plugin_persistedstate_1.createPersistedState)();
app.use(element_plus_1.default, { locale: zh_cn_1.default });
pinia.use(persist);
app.use(pinia);
app.use(router_1.default);
app.mount('#app');
